blog/urls.py
from django.urls import path
from blog.views import blog_list, post_detail, posts_by_categories, search, post_edit, post_delete, \
    post_new, comments_delete

app_name = 'blog'

urlpatterns = [
    path('', blog_list, name='blog_list'),
    path('detail/<int:post_pk>/', post_detail, name='post_detail'),
    path('posts_by_categories/<int:category_pk>/', posts_by_categories, name='posts_by_categories'),
    path('search/', search, name='search'),
    path('post_edit/<int:post_pk>/', post_edit, name='post_edit'),
    path('post_new/', post_new, name='post_new'),
    path('post_delete/<int:post_pk>/', post_delete, name='post_delete'),
    path('comments_delete/<int:comment_pk>/', comments_delete, name='comments_delete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('blog/', include('blog.urls')),
    path('elements/', include('elements.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elements/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'elements'

urlpatterns = [
    path('', product_list, name='elements'),
    path('product_detail/<int:product_pk>/', product_detail, name='product_detail'),
]

pages/urls.py
from django.urls import path
from pages.views import homepage, about_us, contact, photo_filter

app_name = 'pages'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('about_us/', about_us, name='about_us'),
    path('photo_filter/<int:category_photo_pk>/', photo_filter, name='photo_filter'),
    path('contact/', contact, name='contact'),
]

elements/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# from django.urls import reverse


class Product(models.Model):
    title = models.CharField(
        max_length=64,
        verbose_name='наименование'
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )
    image = models.ImageField(
        verbose_name='Картинка',
        blank=True
    )


    def get_average_review_score(self):
        average_score = 0.0
        if self.reviews.count() > 0:
            total_score = sum([review.rating for review in self.reviews.all()])
            average_score = total_score / self.reviews.count()
        return round(average_score, 1)

    def __str__(self):
        return f'{self.title}'


class Review (models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    text = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

elements/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm, Textarea


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = (
            'text',
            'rating',
        )
        widgets = {
            'text': Textarea(attrs={'class': 'form-control shadow px-2', 'rows': 6}),
            'rating': forms.RadioSelect
        }

elements/views.py
from django.shortcuts import render, redirect, get_object_or_404

from elements.forms import ReviewForm
from elements.models import Product, Review
from cart.forms import CartAddProductForm


def product_list(request):
    products = Product.objects.all()
    return render(request, 'elements/elements.html',
                  {
                    'products': products,
                    })


def product_detail(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            cf = review_form.cleaned_data
            author_name = "Имя"
            Review.objects.create(product=product, author=author_name, rating=cf['rating'], text=cf['text'])
            return redirect(
                'elements:product_detail', product_pk=product.pk
            )
    else:
        review_form = ReviewForm()
        cart_product_form = CartAddProductForm()
        return render(request, 'elements/element_detail.html', {
            'product': product,
            'review_form': review_form,
            'cart_product_form': cart_product_form
        })

elements/templates/elements/element_detail.html
{% extends 'elements/elements.html' %}

{% load static %}

{% block content %}


<!--Element section begin-->
<section style="background-color: #787878">

    <div style="background-color: #bdbebd" class="card shadow-custom border-0 col-lg-8 mx-auto">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <img src="{{ product.image.url }}" alt="product_image" width="500px" style="margin-top: 30px; margin-bottom: 30px"
                     class="img-fluid rounded-0">
            </div>
            <div class="col-lg-6">
                <div class="top">
                    <h2 class="mt-4 font-weight-bold text-grey">
                        {{ product.title }}
                    </h2>
                </div>
                <div class="mt-3">
                    {{ product.description|safe }}
                </div>
<!--                {% if product.available %}-->
<!--                <div class="alert alert-success my-3 text-center">-->
<!--                    В наличии-->
<!--                </div>-->
<!--                {% else %}-->
<!--                <div class="alert alert-danger my-3 text-center">-->
<!--                    Временно нет в наличии-->
<!--                </div>-->
<!--                {% endif %}-->
                <hr>
                <div class="review">
                    <span class="font-weight-bold text-grey">
                        Средняя оценка: {{ product.get_average_review_score }}/5.0
                    </span>
                    <div class="mb-3 font-weight-bold">
                        <a href="" class="text-warning" data-toggle="modal" data-target="#myModal" >
                            Оставьте свой отзыв
                        </a>
                    </div>
                </div>
                <div class="mb-4">
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {% csrf_token %}
                        <span class="input-group add-to-cart shadow-custom">
                            <div class="input-group-prepend">
                                <span class="input-group-text
                                font-weight-bold px-3 btn btn-block price">
                                    {{ product.price }}р.
                                </span>
                            </div>
<!--                            <span id="minus" class="input-group-text button_minus px-4">-->
<!--                                - -->
<!--                            </span>-->
                           {{cart_product_form.quantity}}
<!--                            <span id="plus" class="input-group-text button_plus px-4">-->
<!--                                +-->
<!--                            </span>-->
                            <div class="input-group-append">
                                <button class="btn btn-danger px-4 reduce_padding"
                                        type="submit" data-toggle="tooltip"
                                        data-placement="top" title="Добавить в корзину">
                                    <i class="fas fa-shopping-cart"></i>
                                </button>
                            </div>
                        </span>
                    </form>
                </div>
                <div class="btn-group d-flex" style="margin-bottom: 10px">
                    <a href="{% url 'elements:elements' %}"
                       class="btn btn-warning shadow-custom col">
                        Продолжить свой выбор
                    </a>
                    <a href="{% url 'cart:cart_detail' %}" class="btn btn-danger shadow-custom col">
                        Перейти в корзину
                    </a>
                </div>

            </div>
        </div>
    </div>
    <hr class="col-7 mx-auto">
    <div style="background-color: #bdbebd" class="card shadow-custom border-0 col-lg-8 mx-auto mb-3">
        <h3 class="py-2 text-grey">Оценки:</h3>
        {% for review in product.reviews.all %}
        <span class="font-weight-bold py-2 text-grey">
            {{ review.author }} - {{ review.rating }}/5 - {{ review.created }}
        </span>
        <span class="text-justify pb-2">
            {{ review.text }}
        </span>
        <hr>
        {% empty %}
        <span class="pb-2">Пока нет оценок</span>
        {% endfor %}
    </div>
    <!-- MODAL -->
    <div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Что вы думаете об этом?</h5>
                    <button class="close" data-dismiss="modal">×</button>
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="bg-grey">
                            <div class="text-center pt-2">
                                Оценка:
                                <div id="full-stars" class="d-inline text-center">
                                    <div class="rating-group">
                                        <label class="rating__label" for="id_rating_0">
                                            <i class="rating__icon rating__icon--star fa fa-star"></i>
                                        </label>
                                        <input class="rating__input" name="rating"
                                               id="id_rating_0" value="1" type="radio" required>
                                        <label class="rating__label" for="id_rating_1">
                                            <i class="rating__icon rating__icon--star fa fa-star"></i>
                                        </label>
                                        <input class="rating__input" name="rating"
                                               id="id_rating_1" value="2" type="radio" required>
                                        <label class="rating__label" for="id_rating_2">
                                            <i class="rating__icon rating__icon--star fa fa-star"></i>
                                        </label>
                                        <input class="rating__input" name="rating"
                                               id="id_rating_2" value="3" type="radio" required>
                                        <label class="rating__label" for="id_rating_3">
                                            <i class="rating__icon rating__icon--star fa fa-star"></i>
                                        </label>
                                        <input class="rating__input" name="rating"
                                               id="id_rating_3" value="4" type="radio" required>
                                        <label class="rating__label" for="id_rating_4">
                                            <i class="rating__icon rating__icon--star fa fa-star"></i>
                                        </label>
                                        <input class="rating__input" name="rating"
                                               id="id_rating_4" value="5" type="radio" checked required>
                                    </div>
                                </div>
                            </div>
                            <hr class="m-0">
                            <div class="input-field text-center p-2">
                                {{review_form.text}}
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-danger" type="submit">Отправить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</section>
{% endblock %}

elements/templates/elements/elements.html
<!DOCTYPE html>
<html lang="zxx">

{% load static %}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="description" content="Yoga Studio">
    <meta name="keywords" content="Yoga, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Elements</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" type="text/css">
<!--    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">-->
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style_elements.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
</head>

<body style="background-color: #787878">

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section set-bg" data-setbg="{% static 'img/header-bg.png' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="main-menu">
                        <div class="logo">
                            <a href="{% url 'pages:homepage' %}">
<!--                                <img src="{% static 'img/logo.png' %}" alt="">-->
                            </a>
                        </div>
                        <nav class="inner-main-navbar mobile-menu">
                            <ul>
                                <li><a href="{% url 'pages:homepage' %}">Главная</a></li>
                                <li><a href="{% url 'pages:about_us' %}">Фотогалерея</a></li>
                                <li><a href="{% url 'elements:elements' %}">Тренажеры</a></li>
                                <li><a href="{% url 'blog:blog_list' %}">Блог</a></li>
                                <li><a href="{% url 'pages:contact' %}">Расписание и контакты</a></li>
                            </ul>
                        </nav>
                        <div id="mobile-menu-wrap"></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Hero Single Section Begin -->
    <section class="hero-single set-bg spad" data-setbg="{% static 'img/elements_bg2.JPG' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="hero-item">
                        <span class="tickler-text">#bondarevafitnessdoctor</span>
                        <h2 style="color: white">Тренажеры</h2>
                    </div>
                </div>
            </div>
        </div>
<!--        <button class="navbar-toggler" data-toggle="collapse"-->
<!--            data-target="#navbarCollapse">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarCollapse">-->
<!--            <ul class="navbar-nav ml-auto">-->
<!--            <li class="nav-item">-->
<!--            <div class="dropdown-custom">-->
<!--                <a href="{% url 'cart:cart_detail' %}"-->
<!--                class="nav-link text-white drop-btn">-->
<!--                <i class="fas fa-shopping-cart"></i>-->
<!--                        $<span id="cart_price">{{ cart_total_price|floatformat:2 }}</span>-->
<!--                        </a>-->
<!--                    </div>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
    </section>
    <!-- Hero Single Section End -->
   {% block content %}
    <!-- Elements Section Begin -->
    <section class="elements-section spad">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-lg-10 offset-lg-1">
                    <div class="home-title">
                        <span>#bondarevafitnessdoctor</span>
                        <h3>
                            Эксклюзивная линейка физкультурно-оздоровительных тренажеров ручной работы из природных
                            экологически чистых материалов "HEALTH-WOOD"
                        </h3>
                    </div>
                </div>

        {% for product in products %}
            <div class="col-sm-6" style="padding: 5px">
                <div class="card product">
                    <div>
<!--                <div class="item">-->
<!--                <div class="item-image">-->
                        <div>
                            <a href="{% url 'elements:product_detail' product.pk %}">
                                <img src="{{product.image.url}}" alt="image" width="555px">
                            </a>
                        </div>
                        <div>
                        <a href="{% url 'elements:product_detail' product.pk %}"></a>
                        </div>
                    </div>
                    <div class="card-body text-center">
                        <h4><a style="text-decoration: none; color: #464646" href="{% url 'elements:product_detail' product.pk %}">{{ product.title }}</a></h4>
                        <hr>
                        <span>{{ product.price }} рублей</span>
                    </div>

            </div>
        </div>
        {% endfor %}
                <div>
                <h3>Доставка и оплата</h3>
                    <p style="color: #111111"> В настоящее время доставка заказов возможна почтой с оплатой наложенным платежом. Ориентировочная стоимость почтовой пересылки 5 рублей</p>
                    <p style="color: #111111"> Вы всегда можете бесплатно забрать понравившиеся вам тренажеры по адресу нахождения клуба с оплатой на месте.</p>
                </div>

            </div>
              </div>
    </section>
    <!-- Elements Section End -->
        {% endblock %}
   <!-- Footer Section Begin -->
    <footer class="footer-section set-bg" data-setbg="{% static 'img/footer-bg.jpg' %}">
        <div class="container">
            <div class="contact-inner">
<!--                <div class="contact-form">-->
<!--                    <div class="section-title">-->
<!--                        <span>#полсолнух#sunflower</span>-->
<!--                        <h2>Напишите нам</h2>-->
<!--                    </div>-->
<!--                    <form action="#">-->
<!--                        <input type="text" placeholder="Имя">-->
<!--                        <input type="email" placeholder="e-mail">-->
<!--                        <input type="text" placeholder="Тема">-->
<!--                        <textarea placeholder="Сообщение"></textarea>-->
<!--                        <button type="submit" class="submit-btn">Отправить</button>-->
<!--                    </form>-->
<!--                </div>-->
                <div class="row">
                    <div class="col-lg-6">
                        <div class="footer-text">
                            <a href="{% url 'pages:homepage' %}" class="logo"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                            <p>Физические упражнения могут заменить множество лекарств, но ни одно лекарство в мире не может заменить физические упражнения.</p>
                            <ul>
                                <li><a href="https://m.facebook.com/bondarevafitnessdoktor-110829744073699/"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="https://www.instagram.com/bondarevafitnessdoctor/"><i class="fa fa-instagram"></i></a></li>
                            </ul>
<!--                            <div>-->
<!--                            {% if user.is_authenticated %}-->
<!--                            <p>Привет, {{ user.username }}!</p>-->
<!--                            <a href="{% url 'logout' %}">Выйти</a>-->
<!--                            {% else %}-->
<!--                            <p>Вход не выполнен</p>-->
<!--                            <a href="{% url 'login' %}">Войти</a>-->
<!--                            {% endif %}-->
<!--                            </div>-->
                            <div class="copyright text-white">
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

<!--    &lt;!&ndash; Js Plugins &ndash;&gt;-->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/circle-progress.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

<!--    scripts from shop to increase and decrease quantity-->
    <script src="{% static 'js/scripts.js'%}"></script>
<!--    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>     не работают кнопки + и - -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>

</body>

</html>