blog/urls.py
from django.urls import path
from blog.views import blog_list, post_detail, posts_by_categories, search, post_edit, post_delete, \
    post_new, comments_delete

app_name = 'blog'

urlpatterns = [
    path('', blog_list, name='blog_list'),
    path('detail/<int:post_pk>/', post_detail, name='post_detail'),
    path('posts_by_categories/<int:category_pk>/', posts_by_categories, name='posts_by_categories'),
    path('search/', search, name='search'),
    path('post_edit/<int:post_pk>/', post_edit, name='post_edit'),
    path('post_new/', post_new, name='post_new'),
    path('post_delete/<int:post_pk>/', post_delete, name='post_delete'),
    path('comments_delete/<int:comment_pk>/', comments_delete, name='comments_delete'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('blog/', include('blog.urls')),
    path('elements/', include('elements.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elements/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'elements'

urlpatterns = [
    path('', product_list, name='elements'),
    path('product_detail/<int:product_pk>/', product_detail, name='product_detail'),
]

pages/urls.py
from django.urls import path
from pages.views import homepage, about_us, contact, photo_filter

app_name = 'pages'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('about_us/', about_us, name='about_us'),
    path('photo_filter/<int:category_photo_pk>/', photo_filter, name='photo_filter'),
    path('contact/', contact, name='contact'),
]

blog/models.py
from django.db import models

from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    title = models.CharField(
        max_length=48, blank=True, null=True
    )

    def __str__(self):
        return f'{self.title}'


class Post(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name='категория', related_name='posts'
    )
    title = models.CharField(
        max_length=64,
        verbose_name='заголовок',
        blank=True, null=True
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True, null=True
    )
    # text = models.TextField(
    #     verbose_name='текст'
    #)
    text = RichTextUploadingField(
        verbose_name='текст'
    )                                   # CKEditor Rich Text Field
    image = models.ImageField(
        upload_to='blog',
        verbose_name='картинка',
        blank=True, null=True
    )
    published = models.DateField(
        verbose_name='дата публикации',
        default=timezone.now
    )
    # author = models.ForeignKey(
    #     User, on_delete=models.CASCADE,
    #     blank=True, null=True
    # )
    # likes = models.IntegerField(
    #     verbose_name='Like',
    #     default=0,
    #     blank=True, null=True
    # )
    # dislikes = models.IntegerField(
    #     verbose_name='Dislike',
    #     default=0,
    #     blank=True, null=True
    # )

    class Meta:
        ordering = ['-published']

    def __str__(self):
        return f'{self.title}'


class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(
        verbose_name='Текст комментария'
    )
    published_date = models.DateTimeField(
        verbose_name='Дата публикации',
    )
    author = models.CharField(max_length=40, blank=True, null=True, default='', verbose_name='Автор')

    def __str__(self):
        return f'{self.text}'

blog/forms.py
from django import forms
from blog.models import Post, Comments
from django.forms import ModelForm, Textarea


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'category',
            'title',
            'description',
            'text',
            'image'
        )
        widgets = {
            'text': Textarea(attrs={'rows': 10, 'cols': 100}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = (
            'text',
            'author'
        )
        widgets = {
            'text': Textarea(attrs={'rows': 4, 'cols': 40}),
            'author': Textarea(attrs={'rows': 1, 'cols': 20})
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from datetime import timedelta, datetime
from django.db.models import Q
from django.core.paginator import Paginator
from django.views.generic import CreateView

from blog.forms import PostForm, CommentForm
from blog.models import Category, Post, Comments


def blog_list(request):
    categories = Category.objects.all()
    posts = Post.objects.all()
    paginator = Paginator(posts, 5)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    # now = timezone.now()
    # month_ago = now - timedelta(weeks=4)
    # latest_posts = Post.objects.filter(published__gte=month_ago).order_by('-published').distinct()[:5]
    context = {
        'categories': categories,
        'posts': posts,
        # 'latest_posts': latest_posts,
        'page': page,
    }
    return render(
        request,
        'blog/blog.html',
        context
    )


def post_detail(request, post_pk):
    post = Post.objects.filter(pk=post_pk).first()
    comments = Comments.objects.filter(post__pk=post_pk)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.published_date = timezone.now()
            comment.save()
            return redirect('blog:post_detail', post_pk=post.pk)
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/post_detail.html',
                  {
                      'post': post,
                      'comments': comments,
                      'comment_form': comment_form,
                  })


# filter posts by categories

def posts_by_categories(request, category_pk):
    posts = Post.objects.all().filter(category__pk=category_pk)
    categories = Category.objects.all()
    paginator = Paginator(posts, 5)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    context = {
        'categories': categories,
        'posts': posts,
        'page': page,
    }
    return render(
        request,
        'blog/blog.html',
        context
    )

# Search for posts


def search(request):
    subject = request.GET.get('subject')
    posts_search = Post.objects.filter(
                                 Q(title__icontains=subject) |
                                 Q(description__icontains=subject) |
                                 Q(text__icontains=subject)
    )
    paginator = Paginator(posts_search, 5)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    context = {
        'subject': subject,
        'posts_search': posts_search,
        'page': page,
    }
    return render(request, 'blog/search.html', context)


# New post

def post_new(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES)                         # added request.FILES to load files
        if post_form.is_valid():
            post = post_form.save()
            # post.published = timezone.now()
            post.save()
            return redirect('blog:post_detail', post_pk=post.pk)
    else:
        post_form = PostForm()
        return render(request, 'blog/post_edit.html', {'post_form': post_form})


# Edit posts

def post_edit(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'GET':
        post_form = PostForm(instance=post)
        return render(request, 'blog/post_edit.html', {'post_form': post_form})
    else:
        post_form = PostForm(request.POST, request.FILES, instance=post)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.save()
            return redirect('blog:post_detail', post_pk=post.pk)


# Кнопка удалить публикацию
def post_delete(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk).delete()
    return redirect('blog:blog_list')


# Comments delete
def comments_delete(request, post_pk, comment_pk):
    post = Post.objects.get(pk=post_pk)
    comment = get_object_or_404(Comments, pk=comment_pk).delete()
    return redirect("blog:post_detail", post_pk=post.pk)

blog/templates/blog/blog.html
<!DOCTYPE html>
<html lang="zxx">

{% load static %}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="description" content="Bondarevafitnesdoctor">
    <meta name="keywords" content="Yoga, health, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" type="text/css">
<!--    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">-->
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
<!--    <link rel="stylesheet" href="{% static 'css/style_elements.css' %}" type="text/css">-->
</head>

<body style="background-color: #787878">

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section set-bg" data-setbg="{% static 'img/header-bg.png' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-9 offset-md-1">
                    <div class="main-menu">
                        <div class="logo">
                            <a href="{% url 'pages:homepage' %}">
<!--                                <img src="{% static 'img/logo.png' %}" alt="">-->
                            </a>
                        </div>
                        <nav class="inner-main-navbar mobile-menu">
                            <ul>
                                <li><a href="{% url 'pages:homepage' %}">Главная</a></li>
                                <li><a href="{% url 'pages:about_us' %}">Фотогалерея</a></li>
<!--                                <li><a href="{% url 'elements:elements' %}">Тренажеры</a></li>-->
                                <li><a href="{% url 'blog:blog_list' %}">Блог</a></li>
                                <li><a href="{% url 'pages:contact' %}">Расписание и контакты</a></li>
                            </ul>
                        </nav>
                        <div id="mobile-menu-wrap"></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->


    <!-- Hero Single Section Begin -->
    <section class="hero-single set-bg spad" data-setbg="{% static 'img/aboutus_3.JPG' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="hero-item">
                        <span class="tickler-text">#bondarevafitnessdoctor</span>
                        <h2 style="color: white">Блог</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Single Section End -->

{% block content %}
    <!-- Blog Section Begin -->
    <section style="background-color: #787878"  class="blog-section set-bg spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                        {% if posts %}
                    <div class="blog-items">
                        {% for post in page.object_list %}
                        <div class="single-blog">
                            <div class="blog-pic">
                                <img width="730" src="{{post.image.url}}" alt="">
<!--                                        src="{% if post.image %}{{post.image.url}}{% else %}{% static 'img/hero-slider-13.JPG' %}{% endif %}" alt="">-->
                            </div>
                            <div class="blog-text">
                                <span>{{post.published}}</span>
                                <a href="{% url 'blog:post_detail' post.pk %}"><h2>{{post.title}}</h2></a>
                                <ul>
                                    <li>By #bondarevafitnesdoctor</li>
                                    <li>{{post.category}}</li>
                                </ul>
                                <p>{{post.description}}...</p>
                                <a href="{% url 'blog:post_detail' post.pk %}" class="primary-btn blog-btn">Читать</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

<!--                    pagination-->
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-pagination">
                                {% for n in page.paginator.page_range %}

                                    {% if page.number == n %}
                                    <a href="{% url 'blog:blog_list' %}?page={{ n }}">{{n}}<span class="sr-only">(current)</span></a>
                                    {% elif n > page.number|add:-3 and n < page.number|add:3 %}
                                    <a href="{% url 'blog:blog_list' %}?page={{ n }}">{{n}}</a>
                                    {% endif %}

                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>

<!--                    condition for the filter by categories-->

                <div class="col-lg-4">
                    <div class="blog-rt">

<!--                        search form-->
                        <div class="search-form">
                            <form action="{% url 'blog:search' %}" method="get">
                                <input name="subject" type="text" placeholder="Введите тему поиска">
                                <input type="submit" value="Поиск">
                            </form>
                        </div>
<!--                        end of search form-->

                        <div class="categories-list">
                            <h5>Категории</h5>
                            <ul>
                                {% for category in categories %}
                                <li><a style="color: #FFDD8D" href="{% url 'blog:posts_by_categories' category.pk %}">{{category.title}}</a> <span>({{category.posts.count}})</span></li>
                                {% endfor %}
                            </ul>
                            <ul>
                                <li><a style="color: #FFDD8D" href="{% url 'blog:blog_list' %}">Все категории</a></li>
                            </ul>
                        </div>

<!--                        <div class="latest-post">-->
<!--                            <h5>Самые полезные</h5>-->
<!--                            <ul>-->
<!--                                {% for latest_post in latest_posts %}-->
<!--                                <li>-->
<!--                                    <div class="latest-pic">-->
<!--                                        <img src="{% static 'img/latest/latest-1.png' %}" alt="">-->
<!--                                    </div>-->
<!--                                    <div class="latest-text">-->
<!--                                        <span>{{ latest_post.published }}</span>-->
<!--                                        <h6>{{ latest_post.title }}</h6>-->
<!--                                    </div>-->
<!--                                </li>-->
<!--                                {% endfor %}-->
<!--                            </ul>-->
<!--                        </div>-->
                        {% if user.is_authenticated %}
                        <div style="margin-bottom: 35px; margin-left: 25px">
                          <a style="border: 2px solid; border-radius: 10px; padding: 5px; color: white"
                             href="{% url 'blog:post_new' %}">
                              Добавить публикацию
                          </a>
                        </div>
                        {% endif %}
                    </div>
                </div>
<!--                    end of the filter-->

            </div>
        </div>
    </section>
    <!-- Blog Section End -->

{% endblock %}

   <!-- Footer Section Begin -->
    <footer class="footer-section set-bg" data-setbg="{% static 'img/footer-bg.jpg' %}">
        <div class="container">
            <div class="contact-inner">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="footer-text">
                            <a href="{% url 'pages:homepage' %}" class="logo"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                            <p style="color: grey">Физические упражнения могут заменить множество лекарств, но ни одно лекарство в мире не может заменить физические упражнения.</p>
                            <ul>
                                <li><a href="https://m.facebook.com/bondarevafitnessdoktor-110829744073699/"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="https://www.instagram.com/bondarevafitnessdoctor/"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="https://youtube.com/@fitness_doctor"><i class="fa fa-youtube"></i></a></li>
                            </ul>
<!--                            <div>-->
<!--                            {% if user.is_authenticated %}-->
<!--                            <p>Привет, {{ user.username }}!</p>-->
<!--                            <a href="{% url 'logout' %}">Выйти</a>-->
<!--                            {% else %}-->
<!--                            <p>Вход не выполнен</p>-->
<!--                            <a href="{% url 'login' %}">Войти</a>-->
<!--                            {% endif %}-->
<!--                            </div>-->
                            <div class="copyright text-white">
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->


<!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/circle-progress.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

</body>

</html>

blog/templates/blog/post_detail.html
{% extends 'blog/blog.html' %}
{% load static %}

{% block content %}
<section>
        <div class="container">
                <div class="row">

<!--Text of the post begin-->
                    <div class="col-lg-8">
                        <div class="blog-items" style="margin-bottom: 20px; margin-top: 20px">
                            <h3 style="margin: 20px">{{post.title}}</h3>
                            <img width="730" src="{% if post.image %}{{post.image.url}}{% else %}{% static 'img/blog/blog-1.jpg' %}{% endif %}" alt="">
                            <br>
                            {{post.description}}
                            <br>
                            <br>
                            {{post.text|safe}}
                            <br>
                        </div>
                    </div>
<!--Text of the post End-->

<!--                <b style="color: red">Была ли статья для вас полезной?</b><br>-->
                <a style="color: #FFDD8D" href="{% url 'blog:blog_list' %}" class="primary-btn blog-btn">Вернуться к списку статей</a>
                </div>
            {% if user.is_authenticated %}
            {% csrf_token %}
                <div style="margin: 20px">
                    <a style="padding: 5px;border: 2px solid; border-radius: 8px; color: white"
                       href="{% url 'blog:post_edit' post_pk=post.pk %}"> Редактировать статью </a>
                </div>

                <div style="float: right; margin-top: -35px; margin-right: 20px">
                    <a style="padding: 5px;border: 2px solid; border-radius: 8px; color: white"
                       href="{% url 'blog:post_delete' post_pk=post.pk %}"> Удалить статью </a>
                </div>
            {% endif %}
<!--            comments section-->
                <div style="padding-bottom: 50px; padding-top: 20px; font-size: 14px; margin-left: 50px; text-align: justify">
                    <h4>Комментарии ({{comments.count}})</h4>
                    {%for i in comments%}
                    <br><p style="color: #ffc107">{{i.author}}</p>
                    <p style="color: #1b1e21">{{i.text}}</p>
                    <p>{{i.published_date}}</p>
                    {% if user.is_authenticated %}
                    {% csrf_token %}
                <div style="float: right; margin-top: -35px; margin-right: 20px">
                    <a style="padding: 5px;border: 2px solid; border-radius: 8px; color:white"
                       href="#"> Удалить комментарий </a>
                </div>
                    {% endif %}
                    {% endfor %}
                    <form action="." method="POST">
                        {% csrf_token %}
                        <h5 style="margin-top: 40px; margin-bottom: 20px; color: #1b1e21">Оставить комментарий:</h5>
                        {{comment_form.as_p}}
                    <input type="submit" class="primary-btn" value="Добавить">
                    </form>

                </div>
<!--            comments section end-->


        </div>
</section>

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/blog.html' %}
{% load static %}

{% block content %}
<section>
        <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog-items" style="margin-bottom: 20px; margin-top: 20px">
                            <form action="" method="POST" enctype="multipart/form-data">
<!--                                added enctype="multipart/form-data" to work with files-->
                            {% csrf_token %}
                            {{post_form.as_p}}
                            <input type="submit" class="primary-btn" value="Добавить">
                            </form>

                        </div>
                    </div>

                </div>
        </div>
</section>
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/blog.html' %}
{% load static %}

{% block content %}

<section style="background-color: #787878">
        <div class="container">
            <div class="row">

<!--                search results-->
                <div class="col-lg-8">
                     <div class="blog-items" style="margin-bottom: 20px; margin-top: 20px">
                        {% if posts_search %}
                            <h2 style="text-align: left">Результаты поиска "{{ subject }}"</h2><br>
                            {% for item in page.object_list %}
                            <img width="730"
                                        src="{% if item.image %}{{item.image.url}}{% else %}{% static 'img/blog/blog-2.jpg' %}{% endif %}" alt="">
                        <h2>{{ item.title }}</h2>
                        </br>
                        <p>{{ item.description }}</p></br>
                              <a href="{% url 'blog:post_detail' item.pk %}" class="primary-btn blog-btn" style="margin-bottom: 40px">Читать</a>
                            {% endfor %}

<!--                pagination-->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="blog-pagination" style="margin-top: 5%">
                                    {% for n in page.paginator.page_range %}

                                      {% if page.number == n %}
                                              <a href="{% url 'blog:search' %}?page={{ n }}">{{n}}<span class="sr-only">(current)</span></a>
                                      {% elif n > page.number|add:-3 and n < page.number|add:3 %}
                                              <a href="{% url 'blog:search' %}?page={{ n }}">{{n}}</a>
                                      {% endif %}

                                    {% endfor %}
                                </div>
                            </div>
                        </div>
<!--                        end of pagination-->

                        {% else %}
                            <h4 style="text-align: left">По вашему запросу ничего не найдено</h4>
                        {% endif %}
                    </div>
                </div>
<!--                end of search results-->


<!--                    search form-->
                <div class="col-lg-4">
                    <div class="blog-rt">
                        <div class="search-form" style="margin-bottom: 20px; margin-top: 20px">
                            <form action="{% url 'blog:search' %}" method="get">
                                <input name="subject" type="text" placeholder="Введите тему поиска">
                                <input type="submit" value="Поиск">
                            </form>
                        </div>
                    </div>
                </div>
<!--                  end of search form-->

            </div>
        </div>
</section>

{% endblock %}